---
title: "Stat 331/531: Statistical Computing with R"
author: "Professor Kelly Bodwin"
output: rmdformats::readthedown
---
## Contact

#### Professor Kelly Bodwin

**Office:** Discord Sever, the internet.

**Email:** prof.bodwin+stat331@gmail.com


### Course Discord:

For questions of general interest, such as course clarifications or conceptual questions, please use the [Class Discord Server](https://discord.gg/UbXwkxQ).  Refer to the Day One Class Setup
materials for more information on how to effectively use this server.


### Office Hours:

#### Wednesday & Friday, 10am-12pm

(All Office Hours held on Discord.)


## Course Info

**Room:** The Internet

**Times:** NA; Asynchronous

### Learning Objectives:

This course will teach you the basics of R Statistical Software and of statistical computing principles.

After taking this course, you will be able to:

* Work with the RStudio IDE and R Markdown documents.
* Import, manage, and clean data from a wide variety of data sources.
* Visualize and summarize data for informative exploratory data analysis and presentations.
* Write efficient and well-documented R code.
* Program random experiments and simulations from probability models
* Extend your R skills independently through documentation and online resources.

Additionally, it is my hope that you will learn to:

* Contribute to and participate in the R Open Source Community.
* Be thoughtful, deliberate, and ethical in your use of R and similar tools.
* Use R to be playful, creative, and fun!



### Textbook:

There is no required textbook for this course - we will work with free online resources.  

### Equipment

You will require a computer with reliable internet access.  If this requirement
is limiting for you, please contact me ASAP.


## Grade Breakdown

Your grade will consist of the following:

- 5% Check-Ins
- 5% Challenges
- 10% Practice Activities
- 25% Lab Assignments
- 15% Midterm
- 20% Final Project
- 20% Final Exam

## Course Organization

This class is organized into three distinct units.

### Unit 1:  R for Data Science

The first unit will focus on the R language itself.  You will become accustomed to the structure of programming in R, and learn to perform and present basic exploratory data analyses.  

This unit will fairly closely follow Part I of [R for Data Science](https://r4ds.had.co.nz/) by Hadley Wickham.


### Unit 2: Becoming an R Programmer

The second unit will grow your ability to extend your R skills beyond the basics.  
You will learn to work with unusual data types, to write your own functions, to 
program more efficiently and cleanly, and to teach yourself new packages.

This unit will borrow from Parts II and I of [R for Data Science](https://r4ds.had.co.nz/), 
bits and pieces of [Advanced R](https://adv-r.hadley.nz/), and various other online resources.


### Unit 3: Statistical Computing

The final unit of the course will ask you to use your R abilities to implement 
various statistical computing tasks, such as simulation, bootstrapping, and Monte Carlo.  

## Coursework and Check-Ins

As this is an online class, traditional lecture is replaced with online coursework.

These documents will take you through a series of videos, readings, and tutorials
to learn the weeks' material.  Give these the attention and diligence you would
give to an in-class lecture.

Throughout the courswork, you will find short Check-In questions to keep you on 
task.  Make sure you submit your answers to these on Canvas to get credit for
your efforts.  Note that the Canvas Check-In Quizzes can be submitted many times
without penalty - so you should get 100% on this part of the course!



## Practice Activities

Each week, you will be given a Practice Activity to complete, to get the hang of 
the week's necessary R skills.  These activities will always result in a single, 
straightforward correct answer, that you will submit via the Canvas site.  Therefore, 
there is no reason you should not get full credit in this category!

Since these activities are intended to be your first attempt at new skills, they 
are meant to be done with help from me and your peers. I **strongly** suggest that 
you attempt to start the activities before office hours, so you can maximize the 
utility of my help.

Practice Activities are due **Wednesdays at midnight.**


## Lab Assignments

Your typical homework assignments will be weekly labs.  These labs are due on **Fridays at midnight**.  

There are no extensions on lab assignments.  There is a grace period through 
**Sunday at midnight**, during which your lab is not penalized, but you will
not receive Peer Review credit. (10% of the lab grade.)

Labs turned in later than Sunday will not be reviewed, and instead will be quickly
checked for completeness and receive an automatic grade of 50%.

## Challenges

With each Lab Assignment will come a Challenge, asking you to try skills beyond
what is required that week.  Challenges are worth 10 points each, and full credit
is given for any good faith attempt.

At the end of the quarter, the Challenge points are taken out of 100.  However,
there are only 8 lab assignments!  This means that in order to achieve 100/100,
you must submit impressive challenge submissions that earn bonus points.

Extra bonus points beyond 100 earn you extra credit.


### Dates

**Midterm:** Monday, July 27th

**Final Exam:** Friday, September 4th.


## Other Policies

### Participation and Attendance

As this class is asynchronous, there are no participation points.

However, I hope you will attend Office Hours on Discord, and use that platform
and other online tools to interact with your classmates!


### Diversity and Inclusion

It is my goal for everyone to feel safe and comfortable in my class. If there is any way
I can make the course more welcoming for you, please do not hesitate to ask.

In particular, if you have a disability, I will gladly work with you to make this class accessible.

I encourage you to also contact the **Disability Resource Center** *(Building 124, Room 119
or at 805-756-1395)*, who can help you register for extra accomodations such as extended
exam time.

### Cheating and Plagiarism.

Simply put, I will not tolerate cheating. 

Any incident of dishonesty, copying, exam cheating, or plagiarism will be reported to the Office of Student Rights and Responsibilities.

Cheating will earn you a grade of 0 on the assignment and an overall grade penalty of at least 10%.
In circumstances of flagrant cheating, you may be given a grade of F in the course.

For more information about what constitutes cheating and plagiarism, please see
https://academicprograms.calpoly.edu/content/academicpolicies/Cheating.