---
title: "Final Project Guidelines"
author: "Stat 331"
output: rmdformats::readthedown
---

## Overview

For your Final Project in Stat 331, you will use your new skills to create a "deliverable".  This project should be a thoughtful, professional creation that you will be proud to share even after this class is over.

The format of this deliverable is up to you - you have a few options.  Some of these options will earn you additional Challenge Points.  (Recall that any Challenge Points above the 100 required for that grade category are Extra Credit!)


## Groups 

For this project, you  may work in **Groups of 1-4** people.  The project guidelines are the same regardless of group size; however, I will expect `X` deliverables from a group of size `X`. 

That is, a group of four should turn **four** projects, all on the same dataset or general theme.  You *may* duplicate the project options; for example, a group of three might turn in one article and two supporting Shiny apps.

Once you pick a group, *even if you are working alone*, you must join a Final Project group on Canvas.  

Everyone in a group will recieve the same grade, unless concerns are privately expressed to me about member contribution.  Bonus Challenge Points will be divided evenly across group members.


This project is due on **Friday, August 28th**.  (i.e., the last day of the 10-week Summer Session)

## Option A: Data Analysis

Use your skills in the class to perform a formal analysis of a dataset.

This analysis should read like a formal article, such as those that appear in pop science journals like [this one](https://www.scientificamerican.com/).  That is, it should be *formatted* and *polished* - we shouldn't be able to see any code unless it is absolutely necessary, plots and tables should have clear labels, and the article should have a clear narrative flow.

Your analysis should demonstrate your skills from **all 10 weeks** of STAT 331, not just the first few weeks.  An article that simply makes plots and summaries is NOT sufficient.

#### Guidelines

You will turn in to me:

* Your .Rmd source file
    
* Your final report in html or pdf form.


## Option B: Shiny App [+20 Challenge Points]

One of the most exciting features of **R** is the package *Shiny*.  

This package allows users to make fully interactive web applications directly in **R**.

See some examples here: https://shiny.rstudio.com/gallery/

*Shiny* is awesome, and this is the project choice that I would most suggest you choosing, unless you have a strong preference otherwise.

It will take you some extra work to learn how *Shiny* works, and how to build your app.  (Hence the bonus Challenge Points!)  However, I think you'll have fun with your results.

The app should showcase in some way a data analysis.  This analysis can be less formal, and less complex, than Project A.  However, it should not be trivial, and should involve skills from all 10 weeks of STAT 331.


#### Resources

[This site](https://shiny.rstudio.com/tutorial/) has very thorough tutorials.



#### Guidelines

Your final project submission will consist of two things:

* Upload your completed app to shinyapps.io.  At least one of your group members will need to make an account, so that you can upload your app.

* Submit to Canvas a .zip folder containing all relevant (data and code) files



## Option C: A Blogdown Website [+20 Challenge Points]

Have you always wanted to make websites to show off your data analysis?

For the very dedicated, now is your chance!

Use the `blogdown` package to make your very own website in **R**!

This project will involve more learning-on-your-own and frustrating troubleshooting than any of the others.

As a reward (in addition to flex points!), you will have a personal website that you have built.

The site should showcase in some way a data analysis - probably in the form of a small blog post on the site.  This analysis can be less formal, and less complex, than Project A.  However, it should not be trivial, and should involve skills from all 10 weeks of STAT 331.

#### Resources

The resources from [this workshop]([https://summer-of-blogdown.netlify.com/]) will be helpful to you.


#### Guidelines

You will only turn in the link to your website.



## Option D: An R Package [+20 Challenge Points]

Do you have an idea for some functions that you wish existed in **R**, that can make your life easier?

Do you feel like you could write these functions yourself?

Are you feeling ambitious about this project?

Write an **R Package**!

Your package does not need to be ground-breaking or complex; simply creating a few small functions that make people's lives easier is very valueable! 

Your package also does not need to have broad scope.  For example, perhaps you have some data and you find yourself making the same types of plots over and over.  You might consider writing a function that auto-generates a plot, given a few variables of interest.

This is a good project choice if you are excited about the more programming-heavy aspects of **R**.  There will be a lot of extra work involved in documenting your functions and so forth.  (Hence the bonus Challenge Points!)

#### Resources

A good place to start learning about packages is [this blog post](https://hilaryparker.com/2014/04/29/writing-an-r-package-from-scratch/), which walks through the basic steps for a simple package.

Further information can be found at [http://r-pkgs.had.co.nz/](http://r-pkgs.had.co.nz/).  Note, though, that this book will contain a lot of information that you do **not** need for purposes of this assignment.

I highly recommend the `usethis` package, to make a lot of this process easier.


#### Guidelines

You will turn in to me:

* A package folder with, at a minimum:
    + A `/R/` subfolder
    + Package metadata (`DESCRIPTION`)
    + Function documentation (`man/`)
    + Namespaces (`NAMESPACE`)
    
* A short vignette demonstrating the purpose and use of your package.


## Challenge Points

There are a few other ways to earn additional Challenge Points on this assignment. 

Each of these options is worth +10 challenge points.  (You may score for each option only once.)

1. Instead of using an existing online dataset, 
    + collect your data using `rvest` or a similar webscraping package, or
    + use `dbplyr` or similar to read your data from a database like **mySQL**
    
2. As part of your data analysis process, make use of a statistical package that we did not learn in class, such as:
    + caret	Training classification models
    + parsnip	Modeling
    + infer	Inference and hypothesis testing
    + forecast	Predictive models
    + randomForest	Classification
    + zoo	Time series
    + mlr	Modeling
    + gbm	Regression modeling
    + car	ANOVA tables
    + mgcv	Generalized additive models
    + lme4 or nlme	Mixed Effect Models
    + glmnet	Lasso and Elastic Net Regression
    + survival	Tools for survival analysis
    + xts	Time Series Data
    + quantmod	Financial Data

3. As part of your data visualization, make use of a package that we did not learn in class, such as:
    + gganimate	Animated visualization
    + Corrplot	Visualization of correlation matrices
    + rgl	3D visualization
    + ggvis	interactive graphics
    + diagrammeR	Diagram visualization
    + vcd	Visualization of categorical data
    + qcc	Quality control plotting
    + igraph	Networks
    + leaflet	Maps

